services:
  mysql:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_USER: ${ENV_ROOT_USER:root}
      MYSQL_ROOT_PASSWORD: ${ENV_ROOT_PASSWORD:123}
      MYSQL_USER: ${ENV_MYSQL_USER:mysqluser}
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD:321}
    ports:
      - "3307:3306"
    volumes:
      - branches-db:/var/lib/mysql
volumes:
  branches-db: