services:
  mysql:
    image: mysql:9.0.1
    container_name: departamento-reparos
    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - branches-db:/var/lib/mysql
volumes:
  branches-db: