spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: oficina
  datasource:
    url: jdbc:mysql://localhost:3307/departamento?createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER:root}
    password: ${ENV_ROOT_PASSWORD:123}

  sql:
    init:
      schema-locations: classpath:db/schema.sql
      mode: always
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: validate
  threads:
    virtual:
      enabled: true
server:
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
